mysite/home/urls.py
from django.conf.urls import url, include
from home import views


app_name = 'home'

urlpatterns = [
    url(r'^$', views.HomeView.as_view(), name='homepage'),
]

mysite/mysite/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^', include('home.urls')),
    url(r'^notifications/', include('notifications.urls')),
    url(r'^settings/', include('settings.urls')),
    url(r'^admin/', admin.site.urls),
]

mysite/settings/urls.py
from django.conf.urls import url, include
from settings import views


app_name = 'settings'

urlpatterns = [
    url(r'^$', views.SettingsView.as_view(), name='settings-page'),
    url('add_attack/$', views.SubmitAttackView.as_view(), name='attack-view'),
]

mysite/settings/models.py
from django.db import models
from django.utils.translation import ugettext_lazy as _


# Create your models here.

class Attack(models.Model):

    # ATTACK_CHOICES = (
    #     ('SYN Flood Attack', 'SYN Flood Attack'),
    #     ('Christmas Tree Attack', 'Christmas Tree Attack'),
    # )

    name = models.CharField(
        verbose_name=_('Attack Name'),
        help_text=_('The name of the attack being detected.'),
        max_length=50,
        primary_key=True,
    )

    # Bool value which represents whether or not the Attack is being detected currently
    detection = models.BooleanField(
        verbose_name=_('Detection'),
        help_text=_('Bool value which represents whether or not this Attack is being detected.'),
        default=True,
    )

    def __str__(self):
        return '{}: {}'.format(self.name, self.detection)

mysite/settings/forms.py
from django.forms import ModelForm
from .models import Attack
from django.forms.widgets import TextInput


class AttackForm(ModelForm):
    """
    This class is used for creating a form by using the Attack model.
    """

    class Meta:
        model = Attack
        fields = '__all__'

mysite/settings/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.views import View
from .models import Attack

from .forms import AttackForm


class SettingsView(View):

    def get(self, request):
        return render(request, 'settings/settings_page.html', {'attacks': Attack.objects.all()})

    def post(self, request):
        # Grabs all of the attack names
        attacks_names = []
        attacks = Attack.objects.all()
        for attack in attacks:
            attacks_names.append(attack.name)

        for attack in attacks_names:
            # Grab the current attack from the database for later use
            current_attack = Attack.objects.get(name=attack)

            # Check to see what the attack's detection was set to
            detection = request.POST.get(attack, 0)

            # Update the detection value in the database for each Attack
            if detection == 'on':
                current_attack.detection = True
            else:
                current_attack.detection = False

            # Save the updated version of each attack's detection to the database
            current_attack.save()

        return self.get(request)


class SubmitAttackView(View):

    def get(self, request):
        return render(request, 'notifications/submit_form.html', {'form': AttackForm})

    def post(self, request):
        form = AttackForm(request.POST)

        if form.is_valid():
            form.save()
            return HttpResponse('<p>Successfully added form.</p>')

        else:
            return HttpResponse('<p>An error has occured with the POST data sent; the form wasn\'t able to validate \
                                 the form data.</p>')

mysite/settings/templates/settings/settings_page.html
{% extends "home/base.html" %}
{% load static %}
{% load tz %}

{% block head_stylesheets %}
    <link rel="stylesheet" type="text/css" href="{% static "home/home.css" %}"/>
{% endblock %}

{% block head_javascript %}
{% endblock %}

{% block body_content %}
    <div class="banner-container">
        <div class="banner-item">
            <h1>Homepage | Notifications</h1>
        </div>
        <div class="banner-item">
            <a href="{% url 'home:homepage' %}">
                Home
            </a>
        </div>
        <div class="banner-item">
            <a href="{% url 'settings:settings-page' %}">
                Settings
            </a>
        </div>
    </div>

    <br>
    <div>
        <form action="" method="post" enctype="multipart/form-data">
            {% csrf_token %}

            <!-- Loop through the different Attacks -->
            {% for attack in attacks %}

                <!-- Print out each Attack with a checkbox for turning on/off its detection status -->
                {% if attack.detection is True %}
                    <input type="checkbox" name="{{ attack.name }}" checked> {{ attack.name }}
                {% else %}
                    <input type="checkbox" name="{{ attack.name }}"> {{ attack.name }}
                {% endif %}
                <br>

            {% endfor %}

            <br><input name="submit-settings" type="submit" value="UPDATE">
        </form>
        <br>
    </div>

{% endblock %}